### PR TITLE
Added support for missing post conditions

### LINKED ISSUE #213: DeclarativePipelineTest - 'cleanup' post step not working
I'm using DeclarativePipelineTest and trying to run a script with the cleanup post stage. But I get this error:

```
No signature of method: com.lesfurets.jenkins.unit.declarative.PostDeclaration.cleanup() is applicable for argument types: (acs_azure_orchestration$_run_closure1$_closure13$_closure87) values: [acs_azure_orchestration$_run_closure1$_closure13$_closure87@53ac5669]
Possible solutions: sleep(long)
groovy.lang.MissingMethodException: No signature of method: com.lesfurets.jenkins.unit.declarative.PostDeclaration.cleanup() is applicable for argument types: (acs_azure_orchestration$_run_closure1$_closure13$_closure87) values: [acs_azure_orchestration$_run_closure1$_closure13$_closure87@53ac5669]
Possible solutions: sleep(long)
```

Is there a workaround for this?
I see a similar issue has been raised in past too https://github.com/jenkinsci/JenkinsPipelineUnit/issues/211 for 'aborted' and it was fixed via PR https://github.com/jenkinsci/JenkinsPipelineUnit/pull/212.

Also I don't see cleanup here https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/src/main/groovy/com/lesfurets/jenkins/unit/declarative/PostDeclaration.groovy

Minimal repro scenario:
Pipeline script:

```
pipeline {
  agent any

  stages {
    stage ('test') {
      steps {
        echo 'test'
      }
    }
  }

  post {
    always {
      echo 'always'
    }
    cleanup{
      echo 'do cleanup'
    }
  }
}
```
Test script:

```
import com.lesfurets.jenkins.unit.declarative.DeclarativePipelineTest
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

class SomeTest extends DeclarativePipelineTest {
  @Override
  @BeforeEach
  void setUp() throws Exception {
    super.setUp()
  }

  @Test
  void executes_script() {
    runScript('Jenkinsfile')
  }
}
```

### LINKED ISSUE #225: Support missing post declarative post conditions
While attempting to test our pipeline, we noticed that [PostDeclaration.groovy](https://github.com/jenkinsci/JenkinsPipelineUnit/blob/master/src/main/groovy/com/lesfurets/jenkins/unit/declarative/PostDeclaration.groovy) was missing support for the `unsuccessful` [post conditional](https://www.jenkins.io/doc/book/pipeline/syntax/#post). 

I submitted a PR to add it in, but then realized that I wasn't sure of the intended functionality of PostDeclaration. It looks like the support for `changed` condition will only occur when the build status is set to CHANGED:

```java
    def execute(Object delegate) {
        def currentBuild = delegate.currentBuild.result
        if (this.always) {
            executeOn(delegate, this.always)
        }

        switch (currentBuild) {
            case 'SUCCESS':
                executeOn(delegate, this.success)
                break
            case 'FAILURE':
                executeOn(delegate, this.failure)
                break
            case 'ABORTED':
                executeOn(delegate, this.aborted)
                break
            case 'UNSTABLE':
                executeOn(delegate, this.unstable)
                break
            case 'CHANGED':
                executeOn(delegate, this.changed)
                break
        }
    }
```

Since there is no actual jenkins build status of `CHANGED` i could never hit the changed conditioinal in my tests. 

Is the intention to mock this by setting the build status to `CHANGED` or is this a defect? If this is the intended functionality I can re-open my PR to add support for `UNSUCCESSFUL` in a similar fashion. If not, I can take a look at updating this piece of code to support the supported [jenkins build statuses](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/Result.java#L56-L79).

### PR DESCRIPTION
**Pull request by bacarroll**
Fixes #225 
Fixes #213

- Added support for missing post declarative conditionals. 
- Updated the functionality of 'CHANGED'. It was previously driven off of setting a build status of 'CHANGED' which is not a valid build status. 
- Added the ability to set the status of the previous build.
- Added additional tests to validate declarative postconditions.

**Useful Info**
- [Supported declarative post conditionals](https://www.jenkins.io/doc/book/pipeline/syntax/#post)
- [Jenkins build results](https://javadoc.jenkins-ci.org/hudson/model/Result.html)

### CODE REVIEW

**Comment by stchar** [comment]
Looks great, thank you!

**Comment by bacarroll** [comment]
Ready for review.

**Comment by stchar** [comment]
Merged, thank you!

**Comment by IncredibleLou** [comment]
I am looking for this fix :) Any chance it will be released soon?

**Pull request merged**
