### PR TITLE
Fully implement mocking the `bat()` function

### LINKED ISSUE #481: Support for mocking Windows `cmd` shell
### What feature do you want to see added?

There is extensive support for mocking `sh()` calls. I'd like to have the same for `bat()` calls.

One problem with this that I can already foresee comes from replacing this:
```
        helper.registerAllowedMethod('bat', [Map.class], {m->
            if(m.returnStdout){
                return """uno-dos@localhost> "${m.script}"\r\naaa\r\nbbb\r\nccc"""
            }
            return null
        })
```
Here, you have some default mocked behaviour that some code may rely on.

Currently, as a workaround, I'm using this setup code:
```
        // redirect `bat()` to the `sh()` support code
        // Windows `cmd` shell is not specially supported by the framework
        // but handled like just any call. We redirect it to the code used
        // for `sh` in order to get better configurable mocking support.
        this.helper.registerAllowedMethod('bat', [String], { args -> helper.runSh(args) })
        this.helper.registerAllowedMethod('bat', [Map], { args -> helper.runSh(args) })
```
and then use `helper.addShMock(...)` to customize the `bat()` mock behaviour.

I'm willing to create a pull request, but I have a few questions up front:

- Would there be interest at all?
- Should I simply adjust code so that above workaround is implemented automatically? The alternative would be to duplicate the infrastructure provided by the helper class, so that you then get `helper.addBatMock()` and `helper.runBat()`.

### Upstream changes

_No response_

### PR DESCRIPTION
**Pull request by UlrichEckhardt**
Notes:

- The feature this implements is described in #481. (Fixes #481).
- It further depends on #483, so that has to be discussed first.
- I'm new to Groovy, not even with Java experience to help, so be critical.
- The pull request is a draft for now, it's not ready yet.
- I've put separate steps into separate commits, for easier review.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by nre-ableton** [comment]
Before getting too deep in this PR, let's solve #483 and rebase.

**Comment by UlrichEckhardt** [comment]
Just rebased that on top of #483.

There's one question open. Effectively, there are no tests for the `bat()` mock. I was thinking of either copy'n'editing the existing `sh()` tests (in PipelineTestHelperTest.groovy) or to somehow parametrize each test to run once for each of `bat` and `sh`.

**Review by nre-ableton — APPROVED** [review]
Looks great! If you are ready to de-draft and I'll go ahead and merge the PR.

**Comment by nre-ableton** [comment]
Thanks again for your work on this feature @UlrichEckhardt :+1:

**Pull request merged**
