### PR TITLE
Make params immutable for declarative piplines

### PR DESCRIPTION
**Pull request by nre-ableton**
See https://github.com/jenkinsci/JenkinsPipelineUnit/pull/542#issuecomment-1187007209. Should have been part of that PR.

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by nre-ableton** [comment]
I would like to include a failing test with this PR, but don't know enough about the declarative API to do so. Ping @gulyas-istvan-netlock-hu.

**Comment by gulyas-istvan-netlock-hu** [comment]
Hello @nre-ableton,

I wrote a simple declarative example here, it should be work also.

```
pipeline {
    parameters {
        choice(
            name: "TEST_CHOICE",
            choices: ["", "1", "2", "3", "4"], // equivalents "\n1\n2\n3\n4"
        )
        booleanParam(
            name: "TEST_BOOLEAN",
            defaultValue: true
        )
        string(
            name: "TEST_STRING",
            defaultValue: "for test"
        )
    }

    stages {
        stage("Test declarative parameters") {
            steps {
                script {
                    echo "$TEST_CHOICE works"
                    echo "$TEST_BOOLEAN works"
                    echo "$TEST_STRING works"
}}}}}

```

**Comment by gulyas-istvan-netlock-hu** [comment]
> I would like to include a failing test with this PR, but don't know enough about the declarative API to do so. Ping @gulyas-istvan-netlock-hu.

The changes should have to solve this issue

**Review by gulyas-istvan-netlock-hu — APPROVED** [review]
It seems well

**Comment by nre-ableton** [comment]
@gulyas-istvan-netlock-hu Thanks for the test pipeline. However, it passes the unit tests without the changes in https://github.com/jenkinsci/JenkinsPipelineUnit/pull/546/commits/9dcd26b52c4fc37ef21915bf63a5515322c32963. It would be nice to have a test that fails without the changes, so we can prove that https://github.com/jenkinsci/JenkinsPipelineUnit/pull/546/commits/9dcd26b52c4fc37ef21915bf63a5515322c32963 is really necessary.

**Comment by nre-ableton** [comment]
@gulyas-istvan-netlock-hu I've modified your original pipeline so that it failed without the fix. Please have another look at this PR -- if this will fix the issue, then I'll merge and make a new hotfix release.

**Review by gulyas-istvan-netlock-hu — APPROVED** [review]

**Comment by nre-ableton** [comment]
@gulyas-istvan-netlock-hu Thanks!

**Comment by gulyas-istvan-netlock-hu** [comment]
@nre-ableton Thanks!

**Pull request merged**
