### PR TITLE
Fix for #140

### LINKED ISSUE #140: Add support for withMaven()
Please add a default implementation for `withMaven()` so people have an idea how to that.
Here is my version as a reference:

        helper.registerAllowedMethod('withMaven', [Map.class, Closure.class]) { options, c ->
            c.delegate = delegate
            helper.callClosure(c)
        }

### PR DESCRIPTION
**Pull request by digulla**
Implemented withMaven, fixes #140

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [-] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by nre-ableton** [comment]
Ok, thanks! The PR looks pretty good, there are only 2 small issues. First, can you make this change in the code?

```groovy
        helper.registerAllowedMethod('withMaven', [Map, Closure]) { Map args, Closure c ->
```

(To match how the other mocks look).

Second, can you please change the commit message to be a bit clearer? I would suggest simply "Implement withMaven mock". This makes it easier for people to see what the change is about simply by looking at the log history, and not needing to also click on an extra link. Also, if the project should ever move from GitHub to somewhere else, having links in the build history will be confusing.

Thanks!

**Review by nre-ableton — CHANGES_REQUESTED** [review]
Ok, thanks! The PR looks pretty good, there are only 2 small issues. First, can you make this change in the code?

```groovy
helper.registerAllowedMethod('withMaven', [Map, Closure]) { Map args, Closure c ->
```

(To match how the other mocks look).

Second, can you please change the commit message to be a bit clearer? I would suggest simply "Implement withMaven mock". This makes it easier for people to see what the change is about simply by looking at the log history, and not needing to also click on an extra link. Also, if the project should ever move from GitHub to somewhere else, having links in the build history will be confusing.

Thanks!

**Comment by digulla** [comment]
Not sure which commit message you refer to. Is it OK now?

**Comment by digulla** [comment]
> Ok, thanks! The PR looks pretty good, there are only 2 small issues. First, can you make this change in the code?
> 
> ```groovy
> helper.registerAllowedMethod('withMaven', [Map, Closure]) { Map args, Closure c ->
> ```
> 
> (To match how the other mocks look).
> 
> Second, can you please change the commit message to be a bit clearer? I would suggest simply "Implement withMaven mock". This makes it easier for people to see what the change is about simply by looking at the log history, and not needing to also click on an extra link. Also, if the project should ever move from GitHub to somewhere else, having links in the build history will be confusing.
> 
> Thanks!

The GitHub UI is both too simple and too confusing. How do I tell you that I updated the PR? Where is the "push" button?

Is it working now? I can't tell.

**Comment by nre-ableton** [comment]
> > Ok, thanks! The PR looks pretty good, there are only 2 small issues. First, can you make this change in the code?
> > ```groovy
> > helper.registerAllowedMethod('withMaven', [Map, Closure]) { Map args, Closure c ->
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (To match how the other mocks look).
> > Second, can you please change the commit message to be a bit clearer? I would suggest simply "Implement withMaven mock". This makes it easier for people to see what the change is about simply by looking at the log history, and not needing to also click on an extra link. Also, if the project should ever move from GitHub to somewhere else, having links in the build history will be confusing.
> > Thanks!
> 
> The GitHub UI is both too simple and too confusing. How do I tell you that I updated the PR? Where is the "push" button?
> 
> Is it working now? I can't tell.

It's ok, I'll get notified by activity on this PR, since I reviewed it. Anyways, the changes look good; please squash them to the previous commit so that this branch only has one commit. Thanks!

**Comment by digulla** [comment]
How do I squash using the Github web ui?

**Comment by nre-ableton** [comment]
@digulla As far as I know, it's not possible. You should squash locally and force-push.

**Comment by nre-ableton** [comment]
@digulla BTW, I tried to fix this for you, but I don't have permission to force-push to your branch. Because I'd like to make a release today, I'll open up another PR with your changes squashed/cherry-picked and merge that instead.

**Comment by nre-ableton** [comment]
Closing in favor of #431.

**Pull request closed without merging**
