### PR TITLE
With credentials multi

### LINKED ISSUE #287: withCredentials does not support UsernamePasswordMultiBinding
groovy.lang.MissingMethodException: No signature of method: groovy.lang.Binding.getVariable() is applicable for argument types: (java.util.LinkedHashMap$Entry) values: [$class=UsernamePasswordMultiBinding]
Possible solutions: getVariable(java.lang.String), getVariables(), setVariable(java.lang.String, java.lang.Object), hasVariable(java.lang.String)

withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'credID', usernameVariable: 'cred_user', passwordVariable: 'cred_password']])

### PR DESCRIPTION
**Pull request by Willem1987**
Fixes #287

### CODE REVIEW

**Comment by nre-ableton** [comment]
Please remove all indentation changes in this branch, as they make this PR harder to review. I agree that there is some inconsistency in the codebase, but we need a better approach to solving it. This is already on the radar, please see https://github.com/jenkinsci/JenkinsPipelineUnit/issues/237.

**Comment by Willem1987** [comment]
Cleaned up MR

**Comment by nre-ableton** [comment]
Can you please squash all the revert commits so that the branch history only has the relevant changes? Thanks!

**Comment by Willem1987** [comment]
Rebased to 1 commit

**Review by nre-ableton — APPROVED** [review]
Looks great, thanks for the fix! :+1:

**Pull request merged**
