### PR TITLE
Add test for nesting stages including parallel

### PR DESCRIPTION
**Pull request by Willem1987**
Added test to validate #238

### CODE REVIEW

**Comment by nre-ableton** [comment]
Can you please be a bit more descriptive in the PR issue and commit messages? The issue number is not interesting as far as this goes; please tell what problem is being solved. Thanks!

**Comment by Willem1987** [comment]
Basically this is just a unit test, to attempt to reproduce (does not seem to occur). And make sure the functionality does not break again. I am unsure what to state.

**Comment by nre-ableton** [comment]
How about "Add unit test for parallel nested stages"?

**Comment by Willem1987** [comment]
Commit message updated

**Review by nre-ableton — COMMENTED** [review]
Commit 039cb580b11ece5e5e674a2e019613c9aa69bab8 still has a very unclear commit message, as does this pull request title. Can you please fix these?

I guess 039cb580b11ece5e5e674a2e019613c9aa69bab8 might be redundant once you rebase this branch, though.

**Comment by Willem1987** [comment]
Rebased and renamed

**Review by nre-ableton — APPROVED** [review]

**Pull request merged**
