### PR TITLE
Fixed intercepting GCL for Global Shared Libraries

### PR DESCRIPTION
**Pull request by radekl**
There is an issue with Intercepting GCL. The parseClass method is never executed thus making libraries attached by e.g.: `helper.registerSharedLibrary(library)` not able to execute Jenkins native methods (ones registered by `registerAllowedMethod` etc). 

This PR fixes the issue and allows to test the global shared libraries locally.

I guess it also fixes issue #51.

P.S. I haven't removed the old parseClass as I'm not sure if it is not executing all the time or only for this particular case.

### CODE REVIEW

**Comment by radekl** [comment]
Although it works with Allowed Methods it doesn't if the shared library inter-uses methods. Let say that we have following library:
```
vars/
- utils.groovy
- commands.groovy
```
both `utils` and `commands` can use methods registered as allowed methods, but they cannot call methods from themselves. E.g.: `commands.groovy` cannot use `utils.someUtilMethod()`

**Comment by radekl** [comment]
Fixed above with some kind of a dirty hack in a9680fc. I have overwritten loadClass method to forcibly execute `recompile` which executes indirectly the `parseClass` method. Works perfectly for my case where I need to test Shared Libraries.

**Comment by radekl** [comment]
Fixed tests

**Comment by stchar** [comment]
@erikzaadi, sorry for a long response, may I ask you to write a test case.

**Comment by s1apped** [comment]
Hi. any news about it?

**Comment by stchar** [comment]
@s1apped, the pull request needs rebasing and some tests, any help is welcome.

**Comment by radekl** [comment]
Unfortunately I won't be able to participate with this PR anymore. Please feel free to add tests if you can.

**Comment by stchar** [comment]
work is continued in #193

**Pull request closed without merging**
